### ISSUE TITLE
The name of the lircd module is not correct

### ISSUE THREAD

**Issue by leamas** [fedora-selinux/selinux-policy#39]
The lircd module  describes permissions for the /dev/lirc[0-9] devices, defining the type *lirc_device_t*. All this looks fine.

However, I think the module name *lircd* is, well, "not ideal".lircd is a user space daemon which basically isn't  related to the kernel devices in any specific way (although it is the primary user of this interface). IMHO, the kernel selinux module should be named *lirc*, leaving the *lircd* name free for the lircd user space daemon.

While I think we agree on that the module name is wrong, I have no idea if it is worth the hassles of actually changing it. I could name the lircd module e. g., lircd_daemon and live with that. IMHO we need some kind of decision, though.

**Comment by doverride** [comment]
I think you may be confused? See below the lircd module:

https://github.com/fedora-selinux/selinux-policy/blob/rawhide-contrib/lircd.te

As you can see lirc_device_t is not declared there

**Comment by leamas** [comment]
Yes, I am confused. This is basically about issue #38, but I just cannot find any reasonable documentation.  I'll close close this bug, invalid, but the question for me is how to get hold of that lircd.te file. Checking out selinux-policy doesn't seem to do the trick...

**Comment by mgrepl** [comment]
Yes but still lircd module name probably is not ideal. It is something what we were discussing with @doverride  also for other policy modules. 

Basically it is a package name against a service name.

**Comment by doverride** [comment]
@leamas I suppose your confusion is with Git then? You may need to checkout the appropriate branch "rawhide-contrib" (something like git checkout -b rawhide-contrib)

**Comment by mgrepl** [comment]
Good point. I would update wiki on Fedora policy github with an explanation why we have two branches.

**Comment by doverride** [comment]
@mgrepl I am not sure if i understand what you mean, but do not see the problem. I actually like that since the lircd policy module only covers the lircd command and the files it maintains. This makes things more modular and provides better integrity. If you group various domains into a single module then that limits ones options to exclude domains. Simply because they are defined in the same module.

In my policy i actually have seperate modules modules for most commands, whether I think it makes sense or not ( i will leave that up to the user to determine whether it makes sense or not)

For example. I have a nm module and a nmcli module. If you want your policy to cover networkmanager but not nmcli, then you have to option to disable the nmcli module (whether that makes sense or not, its not really up to me to decide) I am just providing flexibility but not putting the two domains inside a single module.

People should use the "semodule -d" more often to tailor their policy to their requirements, and we should make that easier. The first step is to make things actually optional.

**Comment by doverride** [comment]
It also makes the modules smaller.

Modules like "irc" that basically has a single domain that tries to cover all conceivable irc clients are a bad idea. You will end up with a domain that is broader than it need to be.

I rather provide 10 modules each for their own irc client than one that piles them all into a single domain which makes that domain broader than strictly needed thereby degrading integrity it aims to provide.

**Comment by mgrepl** [comment]
My point is we have some module name issues with upstream where we use it in this way (lircd.pp) but upstream uses lirc.pp convention. But I like see you changed your mind. But still I don't see a reason to have systemd-machined,systemd-udevd,.... policies alone for example.

So I believe it is about a balance. There is a chance a CLI tool  will communicate with a service and you will end up with additional unwanted rules if you disable a policy for this CLI tool for example.

**Comment by doverride** [comment]
@mgrepl systemd is suppose to be modular (e.g. systemd-machined is optional) we should support that and also make the systemd-machined policy optional.

But also by seperating these policies you make the modules smaller which provides a clearer view.

**Comment by doverride** [comment]
Oh and yes, you are right. I did change my mind on this topic. I prefer "lircd" now, where i would have prefered "lirc". One never stops learning. However you must also keep in mind that I now maintain my own policy and so i no longer have to work with others and no longer have to compromise on such issues.

**Comment by mgrepl** [comment]
Yeap, I know and I can not agree with all your points here. I still believe it makes sense to merge some domains together. For example cluster services. They do the same things and they do everything and we want to have them under control for a communication with other domains. So I see it as a benefit to have the same domain for them.
 
BUT of course another question is an implementation. Should we have them in a single module? Should we have a module which provides an attribute for them? Still a lot of questions for a discussion. 

The main goal is we want to have a simple/secure/usable policy.

**Comment by doverride** [comment]
@mgrepl I suppose the question is "will it make the policy simple, secure and usable in the long run"

If your customer has a "security" requirement to remove some domain that is piled into a single module that has a bunch of other domains that the customer needs, or if your customer objects to some rule that was added to some domain to support some other "similar" process, and wants to remove it for security reasons, then my bet is that having that stuff seperated will turn out to be more simple/secure/usable, than having it all piled together. We have semodule -d|-e now we only need to use it...

**Comment by mgrepl** [comment]
Sure and I believe it is a key point related to profiling. I can agree have services coming from different products, packages in a single module is probably wrong. This is what I learned. It stops modularity, profiling.

But it is a probably good idea to provide an attribute for them to cover most of rules.

Another story is about services coming from a single package. Here I don't see a big benefit to have them as separate policy modules. They communicate together, do the same things. If so I see them in a single module. If not possible then yes, they should be in separated modules.

**Comment by doverride** [comment]
I think we do not disagree that much but I think we do disagree on when to "assume" or when to "err on the safe side"

I personally choose to not assume at all, and err on the safe side. Software evolves. something might make sense to merge now but it may later turned out the be a bad call. There is no harm in seperating as long as the seperation is actually used, taken advantage of.

Sure if doesnt make sense to have 1001 modules if you don't disable what you do not need.

We will just agree to disagree here. We do not have to agree because SELinux allows us to go our seperate way's. Is it not a beautiful technology ? :smile:

**Comment by mgrepl** [comment]
Yeap, it is ;-)
