### ISSUE TITLE
RFE: Review and turn mozilla_plugin_can_network_connect boolean on

### ISSUE THREAD

**Issue by mgrepl** [fedora-selinux/selinux-policy#74]
https://bugzilla.redhat.com/show_bug.cgi?id=1286177

**Comment by doverride** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

On Fri, Nov 27, 2015 at 04:21:26AM -0800, Miroslav Grepl wrote:
> https://bugzilla.redhat.com/show_bug.cgi?id=1286177
> 

Firefox and other browsers are actively discouraging the use of
plugins. I believe only Flash is still supported, and it does not have
such a good track record when it comes to security.

With that said, opening up network access is not such a big deal as
there should probably be a network firewall blocking this any way.

The irony is though that, Fedora wanted the plugins to be confined even
for unconfined users. I could have told you that this would cause
complaints or bug reports (even if there is a simple boolean to toggle). Now Fedora wants to tear down that confinement by not
targetting the network. This is just setting another precendent in my view.

Fortunately even flash' best day's are in the past.

I do not see why Fedora now want's to remove that little barrier it had
after all this time, and knowing that its just flash, and that flash is
in decline anyway. Why encourage this by not discouraging it.

In my view it is no big deal either way.

- -- 
02DFF788
4D30 903A 1CF3 B756 FB48  1514 3148 83A2 02DF F788
https://sks-keyservers.net/pks/lookup?op=get&search=0x314883A202DFF788
Dominick Grift
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iQGcBAEBCgAGBQJWWFWqAAoJENAR6kfG5xmcNqAL/32GKg7qSExW99Gwnq0xnfY/
Afq2fVYHvO9hDoijLTZ+VSIV4lYA3Q5fnlmrir4fIgMlb4i2TrRsIxUx6XbEq5bQ
F3keGfl/MvlT6IHyTmhD6J/WKE96XGcsjH72pqzykedthY7HakGBrRJYXUjfI3ZG
B0XkqMk28BORpLv4xyc2dhjKXUR6rRJfGVUKLvj/w0r+/O/zmy9YDel2BrIuvZMg
g2WXFJe6B3jZX+xACj5nefVK5Mcf6MiRFqTbWjXDzku1gomJEXnbdqWo478W3vD/
3VYwR4V5JEQEdfcKEjxzaq8G6OdsSE2MUyPA8V5Qk4D2rQDWJthZNkKy1S625Lh/
vz0sUQczPk2Ut4i6Nj0JjQ+5Tn4lSjYyA/iNdW+mcCnmQEW+t5+/lwtYWgTD0B3K
0Fk92Sl9D3kFCpie/khtreeAcRWnA+HzPqYDA1vWcUkfIPO7yKpMybJSY/r782Lk
k7Q5emYNlUpNFs4V7FUhE7xNQjKNDOeX5gDIq1IzPw==
=dMd9
-----END PGP SIGNATURE-----

**Comment by mgrepl** [comment]
Time. We are talking about a time and about a lesson which a time gives us (fortunately).

**Comment by doverride** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

On Fri, Nov 27, 2015 at 05:31:40AM -0800, Miroslav Grepl wrote:
> Time. We are talking about a time and about a lesson which a time gives us (fortunately).  
> 

Please do not take offense but allow me to make a potential time-saving
suggestion.

Instead of forcing selinux policy on users and customers, and then abstracting away
much of the essence of selinux in an futile attempt to make it
acceptable, try a different approach that will not give users and
customers the feeling that they are being treated like
children. Position selinux as a product, an optional added value that is
easily accessible and compelling, and then pour resources into making selinux really user friendly, not by
creating another abstraction layer that aims to hide the essence of
selinux but instead to make it easier to work with it all the while
embracing the technology for what it really is.

Who knows we may be surprised by how willing users, customers are to use
a compelling technology when it is not used to shove your policy down their throats.

I think it is nobel that redhat brought SELinux to the masses and showed
leadership, but i now believe it may have gone about this the wrong way.

Most people do not know SELinux, all they know is the policy that is
crippling their experience by default.

I realise my position is blunt but please do not take offense, as your
success is my success.

- -- 
02DFF788
4D30 903A 1CF3 B756 FB48  1514 3148 83A2 02DF F788
https://sks-keyservers.net/pks/lookup?op=get&search=0x314883A202DFF788
Dominick Grift
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iQGcBAEBCgAGBQJWWGStAAoJENAR6kfG5xmc5s8L/0RjKS81shNzeg4ux0nEfwj3
J/H3J0LrUGuf0bVO4Rr7LC939UBO7MtPlCVo1B04hifFXUx2RrZNi2axYWJedXGO
dd+2Tv5VwyzxMlKSd8Z8UGXopywbnrBZ2EEgjkPqJFGkyQllAWSZDRI0foMdi9TH
MK3qamw0jwcaEazsP/1UEsi1PlIQUjnd/IfQQv3Ijhb9Vcdx+ad2hXWuv6RecoxT
sNrqVsPhjGjSduOlddsqhfjze6oot4IxUmMMO/gHf2XFbdXBl+nsFXBIYXC6gtgE
dhoLWyc+Ddg+WHBZbRmKUgfctD9j47QlzzyxCyj7Na6VenQ9400I8hmodJmH5WGb
DxuJIuYh054TvlEgNCxpEor3MxGcOsQ/DuqastB2L5SfYeXpRiZAWO2/LY3fT3b1
Mtp0jUiprWUofCKl14GyB6LIvP24Bhu0OVaLcnLxk0CZNc83BGTQ4Kjgd+twd93F
UAs6wd4ChpWqpr49cEF7XZDuf0ABgwnQjYk7hchfRg==
=iYKk
-----END PGP SIGNATURE-----

**Comment by mgrepl** [comment]
I believe you did not understand me here. I was talking about a time in the different meaning. I mean you do something (add new policies, new booleans ...) with a clear conviction it is correct. And yes, it can be correct but it can show as a bad way over time.

It is my point here. We learn every day.

**Comment by doverride** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

On Fri, Nov 27, 2015 at 06:38:31AM -0800, Miroslav Grepl wrote:
> I believe you did not understand me here. I was talking about a time in the different meaning. I mean you do something (add new policies, new booleans ...) with a clear conviction it is correct. And yes, it can be correct but it can show as a bad way over time.
> 
> It is my point here. We learn every day.

Thanks, I understood perfectly clear. This is exactly the point i am
making as well, except that I would like to add to that: "fail early"

- -- 
02DFF788
4D30 903A 1CF3 B756 FB48  1514 3148 83A2 02DF F788
https://sks-keyservers.net/pks/lookup?op=get&search=0x314883A202DFF788
Dominick Grift
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iQGcBAEBCgAGBQJWWHAGAAoJENAR6kfG5xmcz+cL/Axh+plX1R07C0oIOv1ANPfx
DqexNoCkONjPZCag//Chcg41pIiwNeCAZP4bPA8SqJP1aNvUOMB/wmn/7+gAcQS/
HwsKb4x4cDIynx4ECVmliOIgzxaeo05YCxUGEqKOO7UKiP3xYSWMT9etabF86cV0
Y/qnkjv84wjmB1yXdWviE3gf0QXT7/hVKLYps8Ii9BGYAbksDADZq02VPAOVtcXH
/+CIfoRdJ6SfXyZroYuvpjIePT2KRP12N+26NABamQA5Pg0Sm2O9gZtLdK7vSN9f
lv482IS/v/XoGUdnAqSTEqIhSyqw67VgmgPDx3tCaCEwqhgcI2P025vfeo30Vn+5
F0cjqkNVnmov5J04K4YN1DkuyYzQoucCQ2hA05bmVaUX1NKAUUPFo4jZFyWCsSnM
ARIaGxDog6YECANNokskLESZQGFRQKFJJkhJu/gjB2g1uKpkbmFp33C3Q0Ds+fuZ
bvjwlMv12iq96PVWLv0BxAtw+xrSflTB7mJtu1nYFA==
=LkRy
-----END PGP SIGNATURE-----

**Comment by mgrepl** [comment]
What I believe is happening.

It is a reason why we create github issues and so on to discuss important things.

**Comment by wrabcak** [comment]
Changed default value of mozilla_plugin_can_network_connect to 'True'. Change is included in selinux-policy-3.13.1-161.fc24. 
Thank you for discussion, closing.
